def generate_itinerary_report(destination: str, total_cost: float, details: str) -> str:
    """
    Generates formatted markdown travel report.

    Args:
        destination (str): Travel destination.
        total_cost (float): Total calculated cost.
        details (str): Itinerary details.

    Returns:
        str: Markdown formatted report.
    """

    report = f"""
# Travel Plan for {destination}

## Trip Details
{details}

## Total Estimated Cost
₹{total_cost}

---

Generated by Multi-Agent Travel Planner
"""
    return report
